In [1]:
import pandas as pd
import numpy as np

In [2]:
# Loading the Diabetes data
df = pd.read_csv(r"C:\Users\HI\Downloads\diabetes_binary_health_indicators_BRFSS2015.csv\diabetes_binary_health_indicators_BRFSS2015.csv")

In [3]:
# Shape of the data
df.shape

(253680, 22)

In [4]:
df.head()

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0              0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1              0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2              0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3              0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4              0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      5.0      18.0      15.0       1.0  0.0   9.0        4.0   
1          1.0      3.0       0.0       0.0       0.0  0.0   7.0        6.0   
2          1.0      5.0      30.0      30.0       1.0  0.0   9.0        4.0   
3          0.0      2.0       0.0       0.0       0.0  0.0  11.0        3.0   
4          0.0      2.0       3.0       0.0       0.0  0.0  11.0        5.0   

   Income  
0     3.0  
1     1.0  
2     8.0  
3     6.0  
4     4.0  

[5 rows x 22 columns]

In [5]:
# Information about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   Diabetes_binary       253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   CholCheck             253680 non-null  float64
 4   BMI                   253680 non-null  float64
 5   Smoker                253680 non-null  float64
 6   Stroke                253680 non-null  float64
 7   HeartDiseaseorAttack  253680 non-null  float64
 8   PhysActivity          253680 non-null  float64
 9   Fruits                253680 non-null  float64
 10  Veggies               253680 non-null  float64
 11  HvyAlcoholConsump     253680 non-null  float64
 12  AnyHealthcare         253680 non-null  float64
 13  NoDocbcCost           253680 non-null  float64
 14  GenHlth               253680 non-null  float64
 15  

In [6]:
# Checking whether there are any null values in the data
df.isnull().sum()

Diabetes_binary         0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [7]:
df.head()

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0              0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1              0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2              0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3              0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4              0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      5.0      18.0      15.0       1.0  0.0   9.0        4.0   
1          1.0      3.0       0.0       0.0       0.0  0.0   7.0        6.0   
2          1.0      5.0      30.0      30.0       1.0  0.0   9.0        4.0   
3          0.0      2.0       0.0       0.0       0.0  0.0  11.0        3.0   
4          0.0      2.0       3.0       0.0       0.0  0.0  11.0        5.0   

   Income  
0     3.0  
1     1.0  
2     8.0  
3     6.0  
4     4.0  

[5 rows x 22 columns]

In [8]:
# Unique Values in Diabetes_binary columns
df['Diabetes_binary'].unique()

array([0., 1.])

In [9]:
# Assigning input features to 'X'
X = df.drop('Diabetes_binary', axis=1)

In [10]:
# Assigning output to 'Y'
Y = df['Diabetes_binary']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
# Splitting the data into training and test data
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.20)

In [13]:
# training data shape
x_train.shape

(202944, 21)

In [14]:
# testing data shape
x_test.shape

(50736, 21)

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
feature_scale = StandardScaler()
feature_scale

StandardScaler()

In [17]:
# Fitting and transforming the training data 
scaled_x_train = feature_scale.fit_transform(x_train)

In [18]:
# Transforming the testing data using the parameters learnt from fitting the training data
scaled_x_test = feature_scale.transform(x_test)

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
log_reg_model = LogisticRegression()
log_reg_model

LogisticRegression()

In [21]:
# Training the Logistic Regression model
log_reg_model.fit(scaled_x_train, y_train)

LogisticRegression()

In [22]:
# Testing the model
y_pred_log_reg = log_reg_model.predict(scaled_x_test)

In [23]:
# Outputs
y_pred_log_reg[:5]

array([0., 0., 0., 0., 0.])

In [24]:
# Returns the probability of the output being in either of the class
y_pred_proba_log_reg = log_reg_model.predict_proba(scaled_x_test)

In [25]:
# Probability that the output is '0' and '1'
y_pred_proba_log_reg[:5]

array([[0.88720178, 0.11279822],
       [0.9943278 , 0.0056722 ],
       [0.98189483, 0.01810517],
       [0.60367409, 0.39632591],
       [0.8592592 , 0.1407408 ]])

In [26]:
from sklearn.metrics import log_loss, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [27]:
log_loss(y_test, y_pred_proba_log_reg)

0.3231073096905122

In [43]:
confusion_matrix(y_test, y_pred_log_reg)

array([[42588,  1012],
       [ 5980,  1156]], dtype=int64)

In [149]:
accuracy_score(y_test, y_pred_log_reg)

0.8617943866288237

In [153]:
f1_score(y_test, y_pred_log_reg)

0.23799174092588568

In [157]:
precision_score(y_test, y_pred_log_reg)

0.5349291646311676

In [161]:
roc_auc_score(y_test, y_pred_log_reg)

0.5655977252795669

In [181]:
recall_score(y_test, y_pred_log_reg)

0.1530398322851153

In [167]:
df.sample()

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
89125              0.0     0.0       0.0        0.0  26.0     1.0     0.0   

       HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
89125                   0.0           1.0     0.0  ...            1.0   

       NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  Age  \
89125          0.0      2.0       0.0       0.0       0.0  1.0  4.0   

       Education  Income  
89125        6.0     8.0  

[1 rows x 22 columns]

In [177]:
df.groupby(by='Diabetes_binary').count()

HighBP  HighChol  CholCheck     BMI  Smoker  Stroke  \
Diabetes_binary                                                        
0.0              218334    218334     218334  218334  218334  218334   
1.0               35346     35346      35346   35346   35346   35346   

                 HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
Diabetes_binary                                                       ...   
0.0                            218334        218334  218334   218334  ...   
1.0                             35346         35346   35346    35346  ...   

                 AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  \
Diabetes_binary                                                            
0.0                     218334       218334   218334    218334    218334   
1.0                      35346        35346    35346     35346     35346   

                 DiffWalk     Sex     Age  Education  Income  
Diabetes_binary                                               
0.0                218334  218334  218334     218334  218334  
1.0                 35346   35346   35346      35346   35346  

[2 rows x 21 columns]

## SGD Classifier Model

In [29]:
from sklearn.linear_model import SGDClassifier

In [33]:
# SGD Classifier model
sgdc_model = SGDClassifier(loss='log_loss', penalty='elasticnet', alpha=0.001, class_weight='balanced', early_stopping=True, max_iter=1010)
sgdc_model

SGDClassifier(alpha=0.001, class_weight='balanced', early_stopping=True,
              loss='log_loss', max_iter=1010, penalty='elasticnet')

In [34]:
# Training the SGD Classifier model
sgdc_model.fit(scaled_x_train, y_train)

SGDClassifier(alpha=0.001, class_weight='balanced', early_stopping=True,
              loss='log_loss', max_iter=1010, penalty='elasticnet')

In [35]:
# Predicted outputs
y_pred_sgdc = sgdc_model.predict(scaled_x_test)

In [36]:
# Predicted probabilities
y_pred_proba_sgdc = sgdc_model.predict_proba(scaled_x_test)

In [41]:
log_loss(y_test, y_pred_proba_sgdc)

0.5371333965323292

In [46]:
recall_score(y_test, y_pred_sgdc)

0.7727017937219731

In [42]:
confusion_matrix(y_test, y_pred_sgdc)

array([[31316, 12284],
       [ 1622,  5514]], dtype=int64)

In [183]:
from sklearn.ensemble import RandomForestClassifier

In [197]:
rfc_model = RandomForestClassifier(n_estimators=120, random_state=42, verbose=True)
rfc_model

RandomForestClassifier(n_estimators=120, random_state=42, verbose=True)

In [199]:
rfc_model.fit(scaled_x_train, y_train)

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:   29.0s


RandomForestClassifier(n_estimators=120, random_state=42, verbose=True)

In [201]:
y_pred_rfc = rfc_model.predict(scaled_x_test)

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    1.9s


In [203]:
f1_score(y_test, y_pred_rfc)

0.2582788331776186

In [205]:
confusion_matrix(y_test, y_pred_rfc)

array([[42347,  1234],
       [ 5911,  1244]], dtype=int64)

In [19]:
from sklearn.metrics import classification_report

In [213]:
print(classification_report(y_test, y_pred_log_reg))

              precision    recall  f1-score   support

         0.0       0.88      0.98      0.92     43581
         1.0       0.53      0.15      0.24      7155

    accuracy                           0.86     50736
   macro avg       0.71      0.57      0.58     50736
weighted avg       0.83      0.86      0.83     50736



## Gradient Boosting Classifier

Now let's train a Gradient Boosting model and evaluate its performance.

In [12]:
from sklearn.ensemble import GradientBoostingClassifier

In [13]:
gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42, verbose=True)
gb_model

GradientBoostingClassifier(random_state=42, verbose=True)

In [14]:
# Training the Gradient Boosting model
gb_model.fit(scaled_x_train, y_train)

      Iter       Train Loss   Remaining Time 
         1           0.7828           26.00s
         2           0.7629           24.78s
         3           0.7473           27.26s
         4           0.7348           27.20s
         5           0.7242           26.34s
         6           0.7138           25.65s
         7           0.7060           25.49s
         8           0.6990           24.92s
         9           0.6929           24.31s
        10           0.6870           24.61s
        20           0.6539           20.31s
        30           0.6406           17.37s
        40           0.6340           14.92s
        50           0.6303           12.48s
        60           0.6280            9.87s
        70           0.6265            7.36s
        80           0.6255            4.87s
        90           0.6246            2.44s
       100           0.6239            0.00s


GradientBoostingClassifier(random_state=42, verbose=True)

In [15]:
# Making predictions with Gradient Boosting model
y_pred_gb = gb_model.predict(scaled_x_test)
y_pred_proba_gb = gb_model.predict_proba(scaled_x_test)

### Gradient Boosting Model Evaluation Metrics

In [20]:
# Gradient Boosting Model Evaluation Metrics
print("=== GRADIENT BOOSTING CLASSIFIER EVALUATION METRICS ===")
print()

print(f"Accuracy Score: {accuracy_score(y_test, y_pred_gb):.4f}")
print(f"Precision Score: {precision_score(y_test, y_pred_gb):.4f}")
print(f"Recall Score: {recall_score(y_test, y_pred_gb):.4f}")
print(f"F1 Score: {f1_score(y_test, y_pred_gb):.4f}")
print(f"ROC AUC Score: {roc_auc_score(y_test, y_pred_gb):.4f}")
print(f"Log Loss: {log_loss(y_test, y_pred_proba_gb):.4f}")
print()

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_gb))
print()

print("Classification Report:")
print(classification_report(y_test, y_pred_gb))

=== GRADIENT BOOSTING CLASSIFIER EVALUATION METRICS ===

Accuracy Score: 0.8672
Precision Score: 0.5809
Recall Score: 0.1662
F1 Score: 0.2585
ROC AUC Score: 0.5734
Log Loss: 0.3111

Confusion Matrix:
[[42826   847]
 [ 5889  1174]]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.88      0.98      0.93     43673
         1.0       0.58      0.17      0.26      7063

    accuracy                           0.87     50736
   macro avg       0.73      0.57      0.59     50736
weighted avg       0.84      0.87      0.83     50736

